# Analyzing borrowers’ risk of defaulting

>Purpose: to prepare a report for a bank’s loan division by determining if a customer’s marital status, income level, and/or number of children has an impact on whether they will default on a loan.

# Summary

A report for a bank's loan division is prepared to analyze borrowers' risk of defaulting by determining if a customer’s marital status, income level, and/or number of children has an impact.

Real number data types were changed to integer types for a cleaner look to the values. Additionally, missing values were noticed in the variables 'days_employed' and 'total_income' which were replaced with each respective column's median value to reduce a significant effect on the median and mean values (in contrast if the missing values were replaced with 0). Negative values for 'days_employed' were changed to 0. Furthermore, the variables 'family_status', 'purpose', 'total_income', and 'children' were simplified further and put into categories for better organization and data presentation.

In terms of influence on repaying a loan on time, the relationship between having children and the aforementioned, according to the data, is that the more children a family has the more likely an applicant will repay a loan on time. In the same fashion, applicants who are married or unmarried are less likely to repay a loan on time as compared to applicants who are divorced or widowed. The data also showed that applicants that have a total income between $10,001−$30,000 are less likely to repay a loan on time, and those making between $30,001-$50,000 are also not likely to repay a loan on time, however not as much as the aforementioned applicants—the applicants that have a higher possibility of repaying a loan on time have a total income of up to $10,000. Of the borrowers who apply for a particular type of loan in the order of most likely to least likely to repay a loan in a timely manner are: wedding, housing, education, car, real estate.

## Open the data file and have a look at the general information. 

In [1]:
import pandas as pd
credit = pd.read_csv('/datasets/credit_scoring_eng.csv')
credit.info()

credit

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


children  days_employed  dob_years            education  education_id  \
0             1   -8437.673028         42    bachelor's degree             0   
1             1   -4024.803754         36  secondary education             1   
2             0   -5623.422610         33  Secondary Education             1   
3             3   -4124.747207         32  secondary education             1   
4             0  340266.072047         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1   -4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1   -2113.346888         38  secondary education             1   
21523         3   -3112.481705         38  secondary education             1   
21524         2   -1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose  
0         40620.102    purchase of the house  
1         17932.802             car purchase  
2         23341.752    purchase of the house  
3         42820.568  supplementary education  
4         25378.572        to have a wedding  
...             ...                      ...  
21520     35966.698     housing transactions  
21521     24959.969        purchase of a car  
21522     14347.610                 property  
21523     39054.888        buying my own car  
21524     13127.587             to buy a car  

[21525 rows x 12 columns]

### Conclusion

The various data types are appropriate for their respective variables, however, we will change the real number data types with the integer types for a cleaner look to the values. Additionally, missing values are noticed in the variables 'days_employed' and 'total_income' which will be addressed below.

## Data preprocessing

### Processing missing values

In [2]:
# locating variables with missing values
missing = credit.isnull().sum()
missing

# analyzing the relationship between 'total_income' average and median to best fill NaN values
credit.sort_values(by='total_income', ascending=True)
print('Average income: {}'.format(credit['total_income'].mean()))
print('Median income: {}'.format(credit['total_income'].median()))

# analyzing the relationship between 'days_employed' average and median to best fill NaN values
credit.sort_values(by='days_employed', ascending=True)
print('Average days employed: {}'.format(credit['days_employed'].mean()))
print('Median days employed: {}'.format(credit['days_employed'].median()))

# replacing 'total_income' NaN values with median value
tot_income_med = credit['total_income'].median()
credit['total_income'] = credit['total_income'].fillna(tot_income_med)

# replacing 'days_employed' NaN values with median value
daysemp_med = credit['days_employed'].median()
credit['days_employed'] = credit['days_employed'].fillna(daysemp_med)

Average income: 26787.56835465867
Median income: 23202.87
Average days employed: 63046.49766147338
Median days employed: -1203.369528770489


2.2 Conclusion

There are missing values in 'days_employed' and 'total_income'. These missing values were present possibly because the applicant(s) chose some kind of nondisclosure of their income. Additionally, missing values in days_employed could mean choice of nondisclosure or they are unemployed. These actual reason could also be deduced from the applicant's income_type. If I were to replace the NaN values with 0, that would significantly affect the average and median values for 'days_employed' and 'total_income'. I elect to replace the NaN values with each respective column's median value because in each case the median is less than the average which implies that high extreme values are pulling the mean up.

### Data type replacement

In [3]:
# changing negative values in 'days_employed' to 0 in order to change values to an integer
credit.loc[credit['days_employed'] < 0, 'days_employed'] = 0
credit['days_employed'] = credit['days_employed'].astype('int64')
credit['days_employed']

# changing 'total_income' values to an integer
credit['total_income'] = credit['total_income'].astype('int64')
credit['total_income']

# cleaning up values for 'children'
credit['children'].value_counts() # looking at unique values for 'children'
credit.loc[credit['children'] == -1, 'children'] = 0
credit['children'].value_counts() # rechecking unique values

0     14196
1      4818
2      2055
3       330
20       76
4        41
5         9
Name: children, dtype: int64

### Conclusion

The negative values for days_employed were inhibiting me from changing the days to a neat integer, and so I changed the negative values for days_employed to 0. Since I cannot inquire the negative values with the client directly I will consider the negative values as the number of days the applicant has NOT worked and because the column name is called days_employed, 0 seems appropriate. Converting total_income to an integer did not pose any challenges.

### Processing duplicates

In [4]:
# processing duplicates in 'education'
credit['education'].value_counts() # looks at unique values in 'education' and their counts
credit.loc[credit['education'] == 0, 'education'] = 'None' # converting 0 value placeholder to 'None'
credit['education'] = credit['education'].str.lower() # lowercasing all values
credit['education'].value_counts() # rechecking unique values

# processing duplicates in 'family_status'
credit['family_status'].value_counts() # looks at unique values in 'family_status' and their counts
credit['family_categorized'] = credit['family_status'] # creating a new family status column for better categorization

# processing duplicates in 'income_type'
credit['income_type'].value_counts() # looks at unique values in 'income_type' and their counts

# processing duplicates in 'purpose'
credit['purpose'].value_counts() # looks at unique values in 'purpose' and their counts
credit['purpose_categorized'] = credit['purpose'] # creating a new purpose column for better categorization

### Conclusion

I looked at the categories of the unique values of each object datatype variable and then combined them as appropriate. The variable 'education' had some values that were spelled the same but was selectively capitalized, and so I converted all of the string values to lowercase. Additionally, there were values of 0 for some applicants to which I changed it to 'None' for consistency. The variables 'family_status' and 'income_type' did not have any duplicate values or categories that needed attention.

I created a new columns called 'purpose_categorized' from 'purpose' and 'family_categorized' from 'family_status' to better categorize the different (but similar general) categories.

All in all, I did not delete any duplicate data because different applicants could be applying for a similar purpose.

### Categorizing Data

In [5]:
# simplifying purposes into a general category
# wedding category
credit['purpose_categorized'] = credit['purpose_categorized'].replace(['to have a wedding', 'having a wedding', 'wedding ceremony'], 'wedding')

# car category
credit['purpose_categorized'] = credit['purpose_categorized'].replace(['to buy a car', 'buying a second-hand car','cars', 
                                                                       'second-hand car purchase', 'to own a car', 'purchase of a car',
                                                                       'buying my own car', 'car purchase'], 'car')
# education category
credit['purpose_categorized'] = credit['purpose_categorized'].replace(['going to university', 'supplementary education', 'to get a supplementary education',
                                                                      'getting an education', 'university education', 'profile education',
                                                                      'getting higher education', 'to become educated'], 'education')
# real estate category
credit['purpose_categorized'] = credit['purpose_categorized'].replace(['real estate transaction', 'building a real estate', 'transactions with commercial real estate',
                                                                      'buy commercial real estate', 'buying property for renting out', 'buy real estate',
                                                                      'transactions with my real estate', 'housing transactions', 'building a property',
                                                                      'property', 'buy residential real estate', 'real estate transactions'], 'real estate')
# housing category
credit['purpose_categorized'] = credit['purpose_categorized'].replace(['purchase of the house', 'purchase of the house for my family',
                                                                      'construction of own property', 'housing renovation', 'purchase of my own house'], 'housing')
    
credit['purpose_categorized'].value_counts() # rechecking unique values

# simplifying family statuses
credit.loc[credit['family_categorized'] == 'civil partnership', 'family_categorized'] = 'unmarried'
credit['family_categorized'].value_counts()

# grouping total_income within certain ranges
def assign_income_group(row):
    assign_income = row['total_income']
    if 0 <= assign_income <= 10000:
        return '$0-$10,000'
    if 10001 <= assign_income <= 20000:
        return '$10,001-$20,000'
    if 20001 <= assign_income <= 30000:
        return '$20,001-$30,000'
    if 30001 <= assign_income <= 40000:
        return '$30,001-$40,000'
    return '$40,001-$50,000'
        
credit['tot_income_categorized'] = credit.apply(assign_income_group, axis=1)
credit['tot_income_categorized'].value_counts()

# simplifying number of children
def assign_child_group(row):
    assign_child = row['children']
    if assign_child == 0:
        return '0'
    if assign_child == 1:
        return '1'
    if assign_child == 2:
        return '2'
    if assign_child == 3:
        return '3'
    return '4+'

credit['children_categorized'] = credit.apply(assign_child_group, axis=1)
credit['children_categorized'].value_counts()

0     14196
1      4818
2      2055
3       330
4+      126
Name: children_categorized, dtype: int64

### Conclusion

There were different ways to describe the same category for the applicant's purpose for a loan so I changed the string value to a certain category based on the description. As for the categorization of family, I reduced the number of categories. I also chose to categorize applicant's 'total_income' in certain ranges since there were so many income specificities. The variable 'children' were better categorized since there was a small sample size of each once applicants claimed they had more than 3 children.

## Answer these questions

- Is there a relation between having kids and repaying a loan on time?

In [6]:
# creating pivot table to compare 'debt' and 'children'
debt_children_pivot = credit.pivot_table(index='children_categorized', values='debt', aggfunc='sum')
debt_children_pivot

debt
children_categorized      
0                     1064
1                      444
2                      194
3                       27
4+                      12

### Conclusion

According to the data, the more children a family has the more likely an applicant will repay a loan on time.

- Is there a relation between marital status and repaying a loan on time?

In [7]:
marital_debt_pivot = credit.pivot_table(index='family_categorized', values='debt', aggfunc='sum')
marital_debt_pivot

debt
family_categorized      
divorced              85
married              931
unmarried            662
widow / widower       63

### Conclusion

According to the data, applicants who are married or unmarried are less likely to repay a loan on time as compared to applicants who are divorced or widowed.

- Is there a relation between income level and repaying a loan on time?

In [8]:
income_debt_pivot = credit.pivot_table(index='tot_income_categorized', values='debt', aggfunc='sum')
income_debt_pivot

debt
tot_income_categorized      
$0-$10,000                58
$10,001-$20,000          550
$20,001-$30,000          697
$30,001-$40,000          242
$40,001-$50,000          194

### Conclusion

According to the data, applicants that have a total income between $10,001-$30,000 are less likely to repay a loan on time. Applicants making between $30,001-$50,000 are also not likely to repay a loan on time, however not as much as the aforementioned applicants. The applicants that have a higher possibility of repaying a loan on time have a total income of up to $10,000.

- How do different loan purposes affect on-time repayment of the loan?

In [9]:
purpose_debt_pivot = credit.pivot_table(index='purpose_categorized', values='debt', aggfunc='sum')
purpose_debt_pivot

debt
purpose_categorized      
car                   403
education             370
housing               250
real estate           532
wedding               186

### Conclusion

Applicants that apply for a loan, from most likely to least likely to repay a particular loan on time, are: wedding, housing, education, car, real estate.